import type { SaaSInfo } from '../types';

const commercetools: SaaSInfo = {
    name: 'Commercetools',
    website: 'https://commercetools.com/',
    type: 'saas',
    storefrontApi: { value: [] },
    adminApi: { value: [] },
    productVariants: { value: { support: 'unknown' }, note: '', urls: [] },
    configurableProducts: { value: { support: 'unknown' }, note: '', urls: [] },
    bundleProducts: { value: { support: 'unknown' }, note: '', urls: [] },
    stockTracking: { value: { support: 'unknown' }, note: '', urls: [] },
    multiWarehouse: { value: { support: 'unknown' }, note: '', urls: [] },
    productSearch: { value: { support: 'unknown' }, note: '', urls: [] },
    facetedSearch: { value: { support: 'unknown' }, note: '', urls: [] },
    productCategories: { value: { support: 'unknown' }, note: '', urls: [] },
    customAttributes: { value: { support: 'unknown' }, note: '', urls: [] },
    tieredPricing: { value: { support: 'unknown' }, note: '', urls: [] },
    assetManagement: { value: { support: 'unknown' }, note: '', urls: [] },
    multiStore: { value: { support: 'unknown' }, note: '', urls: [] },
    multiCurrency: { value: { support: 'unknown' }, note: '', urls: [] },
    multiLanguage: { value: { support: 'unknown' }, note: '', urls: [] },
    promotions: { value: { support: 'unknown' }, note: '', urls: [] },
    voucherCodes: { value: { support: 'unknown' }, note: '', urls: [] },
    freeShipping: { value: { support: 'unknown' }, note: '', urls: [] },
    giftCards: { value: { support: 'unknown' }, note: '', urls: [] },
    guestCheckout: { value: { support: 'unknown' }, note: '', urls: [] },
    orderProcessIsConfigurable: { value: { support: 'unknown' }, note: '', urls: [] },
    adminCreatedOrders: { value: { support: 'unknown' }, note: '', urls: [] },
    multipleFulfillments: { value: { support: 'unknown' }, note: '', urls: [] },
    returns: { value: { support: 'unknown' }, note: '', urls: [] },
    invoiceGeneration: { value: { support: 'unknown' }, note: '', urls: [] },
    customerAccounts: { value: { support: 'unknown' }, note: '', urls: [] },
    customerMultipleAddresses: { value: { support: 'unknown' }, note: '', urls: [] },
    customerOrderHistory: { value: { support: 'unknown' }, note: '', urls: [] },
    customerGroups: { value: { support: 'unknown' }, note: '', urls: [] },
    thirdPartyAuth: { value: { support: 'unknown' }, note: '', urls: [] },
    wishlists: { value: { support: 'unknown' }, note: '', urls: [] },
    adminInterface: { value: { support: 'unknown' }, note: '', urls: [] },
    sso: { value: { support: 'unknown' }, note: '', urls: [] },
    adminInterfaceIsThemeable: { value: { support: 'unknown' }, note: '', urls: [] },
    adminInterfaceLocalizable: { value: { support: 'unknown' }, note: '', urls: [] },
    roleBasedAccessControl: { value: { support: 'unknown' }, note: '', urls: [] }
};

export default commercetools;
